language: ruby
env: DB_CONFIG=travis
rvm:
  - 2.1.10
  - 2.3.3
gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_edge.gemfile
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/activerecord_5.0.gemfile
      env: DB_CONFIG=travis
    - rvm: 2.1.10
      gemfile: gemfiles/activerecord_edge.gemfile
      env: DB_CONFIG=travis
    - rvm: 2.3.3
      gemfile: gemfiles/activerecord_edge.gemfile
      env: DB_CONFIG=travis
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
bundler_args: --without development
before_install:
 - gem update bundler
sudo: false
