sudo: false
language: ruby
env: DB_CONFIG=travis
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
gemfile:
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_edge.gemfile
matrix:
  exclude:
  - gemfile: gemfiles/activerecord_edge.gemfile
    rvm: 2.3.7
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
bundler_args: --without development
before_install:
 - gem update bundler
