language: ruby
env: DB_CONFIG=travis
rvm:
  - 2.0
  - 1.9.3
  - 1.8.7
gemfile:
  - Gemfile
  - gemfiles/Gemfile.activerecord-3.2.x
  - gemfiles/Gemfile.activerecord-3.0.x
  - gemfiles/Gemfile.activerecord-2.3.x
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.activerecord-3.2.x
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.activerecord-3.0.x
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.activerecord-2.3.x
