language: ruby
env: DB_CONFIG=travis
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_edge.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/activerecord_edge.gemfile
      env: DB_CONFIG=travis
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_2.3.gemfile
      env: DB_CONFIG=travis
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_3.0.gemfile
      env: DB_CONFIG=travis
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_edge.gemfile
      env: DB_CONFIG=travis
    - rvm: 2.1.5
      gemfile: gemfiles/activerecord_2.3.gemfile
      env: DB_CONFIG=travis
    - rvm: 2.1.5
      gemfile: gemfiles/activerecord_3.0.gemfile
      env: DB_CONFIG=travis
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
bundler_args: --without development
